services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    vich_uploader.download_handler:
        class: SfCod\VichUploaderEncrypt\VichUploader\Handler\DownloadHandler
        public: true

    vich_uploader.upload_handler:
        class: SfCod\VichUploaderEncrypt\VichUploader\Handler\UploadHandler
        public: true

    vich_uploader.metadata_driver.annotation:
        class: SfCod\VichUploaderEncrypt\VichUploader\Metadata\Driver\AnnotationDriver
        arguments:
           - '@annotation_reader'

    vich_uploader.metadata_driver.xml:
        class: SfCod\VichUploaderEncrypt\VichUploader\Metadata\Driver\XmlDriver
        arguments:
           - '@vich_uploader.metadata.file_locator'

    vich_uploader.metadata_driver.yaml:
        class: SfCod\VichUploaderEncrypt\VichUploader\Metadata\Driver\YamlDriver
        arguments:
            - '@vich_uploader.metadata.file_locator'

    Vich\UploaderBundle\Injector\FileInjectorInterface:
        alias: vich_uploader.file_injector